### ISSUE TITLE
Non contiguous tensor value error in model.save_pretrained()

### ISSUE THREAD

**Issue by ZhanGHanG9991** [Shivanandroy/T5-Finetuning-PyTorch#6]
I encounter this problem today when I fine-tune google-t5/t5-base model and try to save the fine-tuned model.

System Info:
Transformers version: 4.43.4
pytorch version: 2.4.0
Python version: 3.8.19

![image](https://github.com/user-attachments/assets/71cbd172-0899-4417-9a13-67f5c978a096)

**Comment by ZhanGHanG9991** [comment]
This bug is derived from transformers package. It has been solved with PR [fix non contiguous tensor value error in save_pretrained](https://github.com/huggingface/transformers/pull/32422). No more errors!

**Comment by theyorubayesian** [comment]
I still have this issue when using `transformers==4.44.2` with `sentence-transformers==3.1.0`

**Comment by dbyoung18** [comment]
> I still have this issue when using `transformers==4.44.2` with `sentence-transformers==3.1.0`

Happen to encounter the same issue. You may need to upgrade ur transformers to v4.45.0+ due to the fix has been checked in since this version([link](https://github.com/huggingface/transformers/blob/v4.45.0/src/transformers/modeling_utils.py#L2801)).
